# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Ruby', 'Ruby')], default='PYTHON', max_length=100),
        ),
    ]
